name: Build macOS App

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby for CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # CocoaPods compatible version

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build with xcodebuild (ad-hoc signing)
      run: |
        xcodebuild -workspace Muse.xcworkspace \
                   -scheme "Muse Bar" \
                   -configuration Release \
                   -sdk macosx \
                   -derivedDataPath build \
                   CODE_SIGN_IDENTITY="-" CODE_SIGNING_REQUIRED=YES

    - name: Package .app bundle
      run: |
        mkdir -p output
        cp -R build/Build/Products/Release/Muse.app output/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: MuseApp
        path: |
          output/Muse.app
