name: Build macOS App

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby for CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # CocoaPods compatible version

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install

    - name: Install xcpretty
      run: sudo gem install xcpretty


    - name: Build with xcodebuild (ad-hoc signing, verbose)
      run: |
        set -o pipefail && xcodebuild -workspace Muse.xcworkspace \
          -scheme "Muse Bar" \
          -configuration Release \
          -sdk macosx \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="-" CODE_SIGNING_REQUIRED=YES \
        | tee build.log | xcpretty --color

    - name: Upload build log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
    - name: Package .app bundle
      run: |
        mkdir -p output
        cp -R build/Build/Products/Release/Muse.app output/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: MuseApp
        path: |
          output/Muse.app
